<?php
echo "Remote Address is: ";
echo $_SERVER['REMOTE_ADDR'];
echo "<br />";
echo "Remote Host is: ";
echo $_SERVER['REMOTE_HOS'];
echo "<br />";
echo "HTTP Referer is: ";
echo $_SERVER['HTTP_REFERER'];
echo "<br />";
echo "Filename is: ";
echo $_SERVER['PHP_SELF'];
echo "<br />";
echo "Server CGI specification is: ";
echo $_SERVER['GATEWAY_INTERFACE'];
echo "<br />";
echo "Server address is: ";
echo $_SERVER['SERVER_ADDR'];
echo "<br />";
echo "Name of the server is: ";
echo $_SERVER['SERVER_NAME'];
echo "<br />";
echo "Server identification string is: ";
echo $_SERVER['SERVER_SOFTWARE'];
echo "<br />";
echo "Name and revision of the information protocol is: ";
echo $_SERVER['SERVER_PROTOCOL'];
echo "<br />";
echo "Request method is: ";
echo $_SERVER['REQUEST_METHOD'];
echo "<br />";
echo "Timestamp at start of request is: ";
echo $_SERVER['REQUEST_TIME'];
echo "<br />";
echo "Query string is: ";
echo $_SERVER['QUERY_STRING'];
echo "<br />";
echo "Document root directory is: ";
echo $_SERVER['DOCUMENT_ROOT'];
echo "<br />";
echo "Contents of 'Accept' header is: ";
echo $_SERVER['HTTP_ACCEPT'];
echo "<br />";
echo "Contents of 'Accept-Charset' header is: ";
echo $_SERVER['HTTP_ACCEPT_CHARSET'];
echo "<br />";
echo "Contents of 'Accept-Encoding' header is: ";
echo $_SERVER['HTTP_ACCEPT_ENCODING'];
echo "<br />";
echo "Contents of 'Accept-Language' header is: ";
echo $_SERVER['HTTP_ACCEPT_LANGUAGE'];
echo "<br />";
echo "Contents of 'Connection' header is: ";
echo $_SERVER['HTTP_CONNECTION'];
echo "<br />";
echo "Contents of 'Host' header is: ";
echo $_SERVER['HTTP_HOST'];
echo "<br />";
echo "Contents of 'User-Agent' header is: ";
echo $_SERVER['HTTP_USER_AGENT'];
echo "<br />";
echo "HTTPS is: ";
echo $_SERVER['HTTPS'];
echo "<br />";
echo "Remote port is: ";
echo $_SERVER['REMOTE_PORT'];
echo "<br />";
echo "Absolute pathname of script is: ";
echo $_SERVER['SCRIPT_FILENAME'];
echo "<br />";
echo "Server admin is: ";
echo $_SERVER['SERVER_ADMIN'];
echo "<br />";
echo "Server port is: ";
echo $_SERVER['SERVER_PORT'];
echo "<br />";
echo "Server version is: ";
echo $_SERVER['SERVER_SIGNATURE'];
echo "<br />";
echo "Filesystem-based path to script is: ";
echo $_SERVER['PATH_TRANSLATED'];
echo "<br />";
echo "Scripts path is: ";
echo $_SERVER['SCRIPT_NAME'];
echo "<br />";
echo "URI is: ";
echo $_SERVER['REQUEST_URI'];
echo "<br />";
echo "Contents of 'Authorization' header is: ";
echo $_SERVER['PHP_AUTH_DIGEST'];
echo "<br />";
echo "Username is: ";
echo $_SERVER['PHP_AUTH_USER'];
echo "<br />";
echo "Password is: ";
echo $_SERVER['PHP_AUTH_PW'];
echo "<br />";
echo "Authentication type is: ";
echo $_SERVER['AUTH_TYPE'];
echo "<br />";
echo "Pathname information is: ";
echo $_SERVER['PATH_INFO'];
echo "<br />";
echo "Original pathname information is: ";
echo $_SERVER['ORIG_PATH_INFO'];
?>